spring:
  application:
    name: todo
      
  datasource:
    url: jdbc:mysql://database-1.ct6jcofgybfx.us-east-1.rds.amazonaws.com:3306/hr
    username: sourabh
    password: Sourabh123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5000